// config.js — fetches /app/config.json once and caches it.
// config.json is generated by deploy.sh from Terraform outputs and is not secret.
// All other modules import getConfig() to get the runtime configuration.

let _config = null;

export async function getConfig() {
  if (_config) return _config;
  const resp = await fetch('/app/config.json');
  if (!resp.ok) throw new Error(`Failed to load config.json: ${resp.status}`);
  _config = await resp.json();
  return _config;
}
